defaults:
  - preprocessing: default
  - _self_

project:
  name: sar-ship-detection
  seed: 42
  root_dir: ${hydra:runtime.cwd}

paths:
  # data_dir: ${project.root_dir}/data
  raw_dir: ${project.root_dir}/data/raw
  masked_dir: ${project.root_dir}/data/masked

resources:
  eez_geodata: ${project.root_dir}/resources/eez_geodata/eez_v12.shp
  mask_geodata: ${project.root_dir}/resources/mask_geodata/mask_aoi.shp
